name: activity_bloc_builder
description: A code generator companion for activity_bloc
version: 0.0.1
repository: https://github.com/dsvishchov/activity_bloc_builder
issue_tracker: https://github.com/dsvishchov/activity_bloc_builder/issues

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  activity_bloc: ^0.0.1
  analyzer: ">=7.0.0 <8.0.0"
  build: ^2.3.0
  meta: ^1.9.0
  source_gen: ^2.0.0
